import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "~/components/NavBar";
import { useAtom } from "jotai";
import { globalStateAtom } from "~/state/globalState";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>:x</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <Content />
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const [globalState, setGlobalState] = useAtom(globalStateAtom);

  return (
    <div>
      <h1 className="mb-8 text-4xl font-bold text-white">
        Global state is global: {globalState}
      </h1>
    </div>
  );
};
