import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "~/components/NavBar";
import { useSession } from "next-auth/react";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>:x</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">Dis is page
          <Content />
        </div>
        </section>
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const {data: topics, refetch: refetchTopics} = api.topic.getAll.useQuery(
    undefined, 
      {
        enabled: sessionData?.user !== undefined,
      }
    );

    return <div>{JSON.stringify(topics)}</div>
}